backend:
  name: github
  repo: kcplayandwork/penguin-mama-blog
  branch: main
  base_url: https://penguinmama.blog
  auth_endpoint: api/auth

media_folder: public/images
public_folder: /images
locale: zh_Hant

collections:
  - name: blog
    label: 文章管理
    folder: src/content/blog
    create: true
    slug: "{{slug}}"
    extension: md
    fields:
      - label: 標題
        name: title
        widget: string
      - label: 摘要
        name: description
        widget: text
      - label: 分類
        name: category
        widget: select
        options:
          - label: 企鵝寶寶副本
            value: parenting
          - label: 副本裡的大人
            value: working
          - label: 親子行李箱
            value: travel
          - label: 一個人的行李箱
            value: solo
      - label: 發布日期
        name: pubDate
        widget: date
        format: YYYY-MM-DD
      - label: 草稿
        name: draft
        widget: boolean
        default: false
        required: false
      - label: 文章內容
        name: body
        widget: markdown
